// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a music-lib project",
    "title": "Music Library",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/songs": {
      "get": {
        "description": "Return songs",
        "parameters": [
          {
            "type": "string",
            "description": "group name",
            "name": "group",
            "in": "query"
          },
          {
            "type": "string",
            "description": "song name",
            "name": "song",
            "in": "query"
          },
          {
            "type": "string",
            "description": "link",
            "name": "link",
            "in": "query"
          },
          {
            "type": "string",
            "description": "release date",
            "name": "releaseDate",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "page number",
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "limit of pages",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "song list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Song"
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/songs/lyrics": {
      "get": {
        "description": "Return song lyrics",
        "parameters": [
          {
            "type": "integer",
            "description": "song id",
            "name": "id",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "default": 0,
            "description": "couplet number",
            "name": "couplet",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "limit of couplets",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "song lyrics",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "description": "general error",
      "title": "ErrorResponse",
      "allOf": [
        {
          "properties": {
            "error": {
              "type": "object",
              "properties": {
                "message": {
                  "description": "Message",
                  "type": "string"
                }
              }
            }
          }
        }
      ]
    },
    "Song": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string",
          "example": "Muse"
        },
        "id": {
          "type": "integer",
          "example": 1
        },
        "link": {
          "type": "string",
          "example": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
        },
        "lyrics": {
          "type": "string",
          "example": "Ooh baby, don't you know I suffer?"
        },
        "releaseDate": {
          "type": "string",
          "example": "2006-07-16"
        },
        "song": {
          "type": "string",
          "example": "Supermassive Black Hole"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a music-lib project",
    "title": "Music Library",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/songs": {
      "get": {
        "description": "Return songs",
        "parameters": [
          {
            "type": "string",
            "description": "group name",
            "name": "group",
            "in": "query"
          },
          {
            "type": "string",
            "description": "song name",
            "name": "song",
            "in": "query"
          },
          {
            "type": "string",
            "description": "link",
            "name": "link",
            "in": "query"
          },
          {
            "type": "string",
            "description": "release date",
            "name": "releaseDate",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "page number",
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "limit of pages",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "song list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Song"
              }
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/songs/lyrics": {
      "get": {
        "description": "Return song lyrics",
        "parameters": [
          {
            "type": "integer",
            "description": "song id",
            "name": "id",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "default": 0,
            "description": "couplet number",
            "name": "couplet",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 0,
            "description": "limit of couplets",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "song lyrics",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "description": "general error",
      "title": "ErrorResponse",
      "allOf": [
        {
          "properties": {
            "error": {
              "type": "object",
              "properties": {
                "message": {
                  "description": "Message",
                  "type": "string"
                }
              }
            }
          }
        }
      ]
    },
    "ErrorResponseAO0Error": {
      "type": "object",
      "properties": {
        "message": {
          "description": "Message",
          "type": "string"
        }
      }
    },
    "Song": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string",
          "example": "Muse"
        },
        "id": {
          "type": "integer",
          "example": 1
        },
        "link": {
          "type": "string",
          "example": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
        },
        "lyrics": {
          "type": "string",
          "example": "Ooh baby, don't you know I suffer?"
        },
        "releaseDate": {
          "type": "string",
          "example": "2006-07-16"
        },
        "song": {
          "type": "string",
          "example": "Supermassive Black Hole"
        }
      }
    }
  }
}`))
}
