// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostSongsHandlerFunc turns a function with the right signature into a post songs handler
type PostSongsHandlerFunc func(PostSongsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSongsHandlerFunc) Handle(params PostSongsParams) middleware.Responder {
	return fn(params)
}

// PostSongsHandler interface for that can handle valid post songs params
type PostSongsHandler interface {
	Handle(PostSongsParams) middleware.Responder
}

// NewPostSongs creates a new http.Handler for the post songs operation
func NewPostSongs(ctx *middleware.Context, handler PostSongsHandler) *PostSongs {
	return &PostSongs{Context: ctx, Handler: handler}
}

/*
	PostSongs swagger:route POST /songs postSongs

Create song
*/
type PostSongs struct {
	Context *middleware.Context
	Handler PostSongsHandler
}

func (o *PostSongs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSongsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
